In [ ]:
# Q2 : In iris.csv there are 150 samples containing following features.
# •	Sepal Length
# •	Sepal Width
# •	Petal Length
# •	Petal Width

# Using above 4 features , classify a flower in one of the three categories,
# •	Setosa
# •	Versicolour
# •	Virginica

# Apply decision tree and Random forest for this problem  and compare the result

: 

In [1]:
#Import Libraries (pandas and numpy)
import numpy as np
import pandas as pd

# Import Dataset

In [2]:
dataset=pd.read_csv("iris.csv") # Read the dataset using pandas

In [3]:
dataset.head() # Check the top 5 records of the dataset

Unnamed: 0  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0           0                5.1               3.5                1.4   
1           1                4.9               3.0                1.4   
2           2                4.7               3.2                1.3   
3           3                4.6               3.1                1.5   
4           4                5.0               3.6                1.4   

   petal width (cm)  target flower_name  
0               0.2       0      setosa  
1               0.2       0      setosa  
2               0.2       0      setosa  
3               0.2       0      setosa  
4               0.2       0      setosa

In [4]:
dataset.info() # Get the information about the type of data used in the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         150 non-null    int64  
 1   sepal length (cm)  150 non-null    float64
 2   sepal width (cm)   150 non-null    float64
 3   petal length (cm)  150 non-null    float64
 4   petal width (cm)   150 non-null    float64
 5   target             150 non-null    int64  
 6   flower_name        150 non-null    object 
dtypes: float64(4), int64(2), object(1)
memory usage: 8.3+ KB


In [5]:
dataset.isnull().sum() # Check if null values(misiing value) is present in the dataset or not

Unnamed: 0           0
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
flower_name          0
dtype: int64

# Separate the dependent and independent variables

In [6]:
x=dataset.iloc[:,1:-2].values # Feature variable(independent variable) matrix
y=dataset.iloc[:,-2].values # Target variable(dependent variable) vector

In [7]:
# x

In [8]:
# y

# Split the dataset into training and test data

In [9]:
from sklearn.model_selection import train_test_split # Import train_test_split method from the sklearn package
# Divide the dataset into training and test data by providing the test size and random state which decides whether the data should be splitted randomly or not 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [10]:
# x_train

In [11]:
# x_test

In [12]:
# y_train

In [13]:
# y_test

# ***DECISION TREE------***

#           Fit the Decision Tree Model

In [14]:
from sklearn.tree import DecisionTreeClassifier # Import the DecisionTreeClassifier class from the sklearn package
dt=DecisionTreeClassifier(criterion="entropy")# Create an instance of the class and mention the technique for Attribute selection 
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

# Predicting the test result

In [15]:
y_pred=dt.predict(x_test)# Predict the values for the test data

# Check the Accuracy of the Model

In [16]:
from sklearn.metrics import confusion_matrix  # Import the confusion_matrix method from the sklearn package
confusion_matrix(y_test,y_pred) # Pass the actual values and the predicted values to the confusion_matrix method
# From the confusion matrix we got to know that the model predicts 29 corect values from 30 test values

array([[11,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  6]], dtype=int64)

In [17]:
from sklearn.metrics import accuracy_score # Import the accuracy_score method from the sklearn package
accuracy_score(y_test,y_pred) # Pass the actual values and the predicted values to the accuracy_score method to check the accuracy of the model

0.9666666666666667

In [18]:
y_pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2], dtype=int64)

In [19]:
y_test

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 1, 2], dtype=int64)

# ***RANDOM FOREST---------***

# Fit the Random Forest model

In [20]:
from sklearn.ensemble import RandomForestClassifier # Import the RandomForestClassifier from the sklearn package
# Create instance of the class and pass no of decision trees that we need in the forest and the technique to be used to select the Attributes for the tree.
rfc=RandomForestClassifier(n_estimators=8,criterion="entropy")
rfc.fit(x_train,y_train) # Train the model using the training data

RandomForestClassifier(criterion='entropy', n_estimators=8)

# Predicting the test result

In [21]:
y_pred=rfc.predict(x_test)# Predict the values for the test data

# Check the Accuracy of the Model

In [22]:
from sklearn.metrics import confusion_matrix# Import the confusion_matrix method from the sklearn package
confusion_matrix(y_test,y_pred)# Pass the actual values and the predicted values to the confusion_matrix method
# From the confusion matrix we got to know that the model predicts 29 corect values from 30 test values(same as the Decision tree)

array([[11,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  6]], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score # Import the accuracy_score method from the sklearn package
accuracy_score(y_test,y_pred)# Pass the actual values and the predicted values to the accuracy_score method to check the accuracy of the model

0.9666666666666667

# ***We saw that the accuracy of both the Decision tree and the Random Forest Model are same i.e 96.6%***